### ISSUE TITLE
REQ 1 Como administrador deseo dar de alta un médico

### ISSUE THREAD

**Issue by ismaelpadilla2007** [Sistemas-de-Software/WebAppMedOffices#1]
No lo crea desde la interfaz gráfica

**Comment by ernestoaguaysol** [comment]
Aclaración: el REQ solo pide el alta de médico

**Comment by alandavidg** [comment]
Deja Guardar Teléfono y Celular con Letras

**Comment by ernestoaguaysol** [comment]
Listo, se corrigió que el Teléfono y Celular sean solo con números

**Comment by alandavidg** [comment]
Sería mejor hacer la carga de especialidad en la pantalla de Alta de Médicos?

**Comment by ernestoaguaysol** [comment]
se agregó la carga de especialidad en el alta de médico

**Comment by alandavidg** [comment]
Quedó bárbaro!!! Muy bueno

**Comment by alandavidg** [comment]
Agregar días y horarios que el médico atenderá

**Comment by ernestoaguaysol** [comment]
Listo, ahora en **Cargar Turnos** si se intenta cargar turnos a un Médico que no tiene consultorio (y por ende no tiene días de atención ni horarios) saldrá una alerta que  dice: "El Médico no tiene Consultorio ni Horario de Atención asignados"

**Comment by alandavidg** [comment]
Al cargar la duración del turno, permite poner números negativos y 0, estaría bueno que el mínimo sea 10 minutos o algo por el estilo. CP-26 (Bug-10)

**Comment by ernestoaguaysol** [comment]
Listo

**Comment by alandavidg** [comment]
Al editar la especialidad, permite poner valores menores a 10 minutos (Bug-14)

**Comment by ernestoaguaysol** [comment]
Bug 14 corregido
