### ISSUE TITLE
ACT. 6 Tener en cuenta la validación de horarios al asignar consultorio a médicos.

### ISSUE THREAD

**Issue by ismaelpadilla2007** [Sistemas-de-Software/WebAppMedOffices#13]
No valida.
Se pueden cargar dos turnos en el mismo dia y horario a dos médicos distintos

**Comment by ernestoaguaysol** [comment]
Lo valida pero no lanza ninguna alerta

**Comment by ismaelpadilla2007** [comment]
Realizado!

**Comment by alandavidg** [comment]
No pude hacer el update-database del último commit.
En la última actualización que tengo deja agregar en el mismo día y hora dos salas distintas a un mismo médico y una sala a dos médicos distintos.

**Comment by ismaelpadilla2007** [comment]
Arreglado!

**Comment by alandavidg** [comment]
Me dejó guardar un consultorio en el mismo día y horario que estaba asignado a otro médico.
Por otro lado, en las veces que no me deja guardar, que el mensaje sea más específico que "el modelo no es válido".
También estaría bueno que en consultorios asignados (aparece luego de asignar un consultorio a un médico), aparezca apellido y nombre en vez de solo nombre

**Comment by ismaelpadilla2007** [comment]
Esta vez si se arreglo la validación. 
Se cambio el mensaje arrojado por "El medico o el consultorio se encuentra ocupado", más adelante se va a realizar mas especifico por ejemplo, el medico se encuentra en otra sala o el consultorio ya se encuentra ocupado entre ese rango horario.
En la vista de los consultorios asignados se agrego que aparezca el apellido del medico.

**Comment by alandavidg** [comment]
Buenisimo! 

Por otro lado, es difícil pegarle a un día y horario en que justo la sala y el médico estén libres, por lo tanto, estaría bueno que seleccionando el médico y la sala, aparezcan los días y horarios libres para asignarla

**Comment by alandavidg** [comment]
Validar y...
Por otro lado, es difícil pegarle a un día y horario en que justo la sala y el médico estén libres, por lo tanto, estaría bueno que seleccionando el médico y la sala, aparezcan los días y horarios libres para asignarla

**Comment by ismaelpadilla2007** [comment]
Primero la validación, después veo lo otro

**Comment by alandavidg** [comment]
Valida que el consultorio no esté asignado a otro médico, pero si el médico está en una sala en un día y horario, deja asignarlo a otra sala superponiendo día y horario (CP-03)

**Comment by alandavidg** [comment]
Testeado con Casos de Prueba CP-06 y CP-07
