### ISSUE TITLE
ACT. 5 En asignar consultorio, sacar turno (mañana, tarde, noche), ya que con el rango horario alcanza y es más específico.

### ISSUE THREAD

**Issue by ismaelpadilla2007** [Sistemas-de-Software/WebAppMedOffices#14]
Aún está en la pantalla

**Comment by ernestoaguaysol** [comment]
Al Enum TrabajoTurno borralo del modelo AtencionHorario definitivamente para que no nos genere problemas a futuro. También hay que sacarlo del seed.

**Comment by ismaelpadilla2007** [comment]
Realizado!
