### ISSUE TITLE
ACT. 8 En detalle de Paciente, agregar "cancelar turno".

### ISSUE THREAD

**Issue by ernestoaguaysol** [Sistemas-de-Software/WebAppMedOffices#15]

**Comment by ismaelpadilla2007** [comment]
Elimina el turno de la base de datos, solo tendría que cambiarle de estado a "disponible" o "canceladoxpaciente"

**Comment by alandavidg** [comment]
Buenísima la tarea de agregar el botón, pero la funcionalidad de cambiar paciente de turno (Req-Id-29) tiene como CoS "El sistema permitirá desasignar un paciente a un turno, pudiendo asignarlo en otro y quedando registrado el último cambio."
Por lo tanto, estaría bueno que luego de eliminar el turno, vaya a la pantalla de asignar turnos.
Por otro lado, cambiar el texto en inglés por castellano y usar el formato de las demás pantallas
