### ISSUE TITLE
REQ 2 Como administrador deseo editar datos de un médico

### ISSUE THREAD

**Issue by ismaelpadilla2007** [Sistemas-de-Software/WebAppMedOffices#19]
No puse visible el mail porque corresponde al logueo.

**Comment by ernestoaguaysol** [comment]
Hay que cambiar el texto en español, y darle color a los botones. Eso es lo que se podría encargar @Drojas79 
Pero también no deja editar, sale una alerta de error al validar el modelo
![image](https://user-images.githubusercontent.com/19298564/95537387-fd6d3f00-09c3-11eb-8e3f-6c05be9e9af7.png)

**Comment by Drojas79** [comment]
Bien yo hago eso por ahora y reviso las pantallas que faltan arregla, y veo esto que no deja editar

**Comment by ismaelpadilla2007** [comment]
Ya deja editar, solo habría que bloquear el mail para que no cambien el usuario. 
Yo intente poner esto  (@disabled = "disabled") en la view de edit, pero no me funciono, lo van a poder ver en el cambio que se llama "Fix, Req 2" 
Linea que se quiso deshabilitar la edición:
@Html.EditorFor(model => model.UserName, new { htmlAttributes = new { @class = "form-control" , @disabled = "disabled"} })

**Comment by ernestoaguaysol** [comment]
Es verdad, hay que ver si conviene o no que permita editar el UserName ya que está ligado al las Tablas de Login **AspNetUser**, para mí no debería poder editarse, la Gestión de Login debería estar aparte si en algún momento aparece como requerimiento. 

Lo que yo haría es ocultar ese campo como lo hace con el Id, por ejemplo:
```

<div class="form-horizontal">
    <h4>Medico</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(model => model.Id)
    @Html.HiddenFor(model => model.UserName)
....
```

Y esto borrarlo:
```

    <div class="form-group">
        @Html.LabelFor(model => model.UserName, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.UserName, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.UserName, "", new { @class = "text-danger" })
        </div>
    </div>
```

**Comment by ismaelpadilla2007** [comment]
Listo!
