### ISSUE TITLE
REQ 20 Como médico deseo imprimir la ficha médica del paciente

### ISSUE THREAD

**Issue by ernestoaguaysol** [Sistemas-de-Software/WebAppMedOffices#20]

**Comment by ernestoaguaysol** [comment]
Descarga básica con la Ficha Médica del paciente sin estilos

**Comment by alandavidg** [comment]
Deja hacerlo solo cuando vas desde pacientes del día. Desde buscar pacientes no permite esa opción

**Comment by ernestoaguaysol** [comment]
Listo, ahora se puede cargar desde la Buscar Pacientes

**Comment by alandavidg** [comment]
Cada médico puede descargar la ficha de todos los pacientes, faltaría que solo pueda ver y descargar solo las de sus pacientes

**Comment by ernestoaguaysol** [comment]
Lo mismo de del REQ 18

https://github.com/Sistemas-de-Software/WebAppMedOffices/issues/9#issuecomment-707395807

**Comment by alandavidg** [comment]
Dar Formato

**Comment by alandavidg** [comment]
Quedó bárbaro. Faltaría que la ficha médica incluya la historia clínica

**Comment by ernestoaguaysol** [comment]
Listo

**Comment by alandavidg** [comment]
Lo hace desde turnos del día, si entrás desde buscar paciente no imprime con el formato correcto (M-26)
