### ISSUE TITLE
REQ 16 Como secretaria deseo consultar los turnos por médico

### ISSUE THREAD

**Issue by ismaelpadilla2007** [Sistemas-de-Software/WebAppMedOffices#21]

**Comment by ernestoaguaysol** [comment]
Esto me fue asignado por que se resuelve en otro REQ ? sí es así cual es?

**Comment by ismaelpadilla2007** [comment]
Porque realizaste el ACT. 3

**Comment by alandavidg** [comment]
Que aparezcan solo los turnos posteriores a la fecha actual, tanto en la búsqueda por especialidad o médico

**Comment by ernestoaguaysol** [comment]
Si es desde **Turnos Disponibles**  Opciones **Médico** o **Especialidad** ese caso ya está resuelto.

**Comment by alandavidg** [comment]
Ese sería el Req 12, los turnos que tiene disponibles para ser asignados. Ese está bien.
Este requisito sería de la pantalla de turnos reservados, es decir, turnos que tiene ocupado el médico

**Comment by ernestoaguaysol** [comment]
CoS: El sistema permitirá consultar los turnos ocupados que tiene asignado cada médico o cada especialidad.

**Comment by ernestoaguaysol** [comment]
No termino de entender en que se diferencia esto en lo hecho en la [ACT 3](https://github.com/Sistemas-de-Software/WebAppMedOffices/issues/17) si son los turnos reservados por médicos, especialidad o paciente.

**Comment by alandavidg** [comment]
Solo faltaba que muestre turnos reservados a partir de la fecha de hoy. Ahora no puedo llegar a los turnos reservados, porque al clickear turnos reservados luego de elegir paciente especialidad o médico me aparece el error de "Invalid column name 'NroAfiliado'."

**Comment by ernestoaguaysol** [comment]
Listo
- [x]  turnos reservados a partir de la fecha de hoy
