### ISSUE TITLE
REQ 11 Como secretaria deseo imprimir el comprobante del turno

### ISSUE THREAD

**Issue by ismaelpadilla2007** [Sistemas-de-Software/WebAppMedOffices#22]
Los comprobantes se pueden ver en turnos reservados

**Comment by ernestoaguaysol** [comment]
1) creo que la descarga debería aparecer en la misma pantalla cuando se le asigna un turno, o en otra pantalla igual pero con los detalles del turno, ya que es un comprobante que lo va a descargar ni bien se asigna/confirma el turno.

2) en el PDF los datos salen alineados y no se ven muy bien.

3) ahora cuando se termina de asignar un turno se redirige a la acción TurnosReservadosInicio, lo que digo en el punto 1 es que hagas otra vista y que la redirijas ahí con los mismos datos pero sin el botón asignar (por que ya fue asignado) pero con el botón de descarga.

**Comment by ismaelpadilla2007** [comment]
Se mejoro el posicionamiento del comprobante, para poder visualizarlos tendrán que dirigirse a turnos reservados -> buscar por médicos y seleccionar ver comprobantes. 
Cuando esten de acuerdo al posicionamiento se replicara en las demás búsquedas.

**Comment by ernestoaguaysol** [comment]
dale, dajalo así luego vemos.

**Comment by alandavidg** [comment]
Solo desde Turnos reservados por médico se puede visualizar el comprobante. 
Faltaría cuando se busca por especialidad y por paciente. 
Por otro lado, como una idea, tal vez también luego de asignar un turno que aparezca directamente esta pantalla en vez de la de turnos resevados.

**Comment by ismaelpadilla2007** [comment]
Se replico el comprobante en especialidad y paciente
Sobre lo segundo lo podemos anotar como mejora.

**Comment by alandavidg** [comment]
Dale, sería una buena mejora

**Comment by alandavidg** [comment]
Dar Formato
