### ISSUE TITLE
REQ 14 Como secretaria deseo cancelar turnos por un médico

### ISSUE THREAD

**Issue by ismaelpadilla2007** [Sistemas-de-Software/WebAppMedOffices#23]

**Comment by alandavidg** [comment]
Desde qué pantalla puedo acceder? Lo hice desde Detalle del paciente y el turno se canceló, pero no se eliminó. Si se cancela por parte del médico significa que el turno deja de existir. (CP-35  -> Bug-12)

**Comment by alandavidg** [comment]
También lo hice desde turnos reservados

**Comment by alandavidg** [comment]
Lo mismo, si lo cancela un médico, el turno tiene que desaparecer. No encuentro la pantalla donde se cancele por médico. (CP-35 -> Bug-12)

**Comment by alandavidg** [comment]
Está cancelando por turno, osea, por hora específica de un día. Cumple esa parte, falta ACT06  (M6 del 15/10) y quedaría completo el req
