### ISSUE TITLE
REQ 29 - Como secretaria deseo cancelar un turno por paciente

### ISSUE THREAD

**Issue by ismaelpadilla2007** [Sistemas-de-Software/WebAppMedOffices#24]

**Comment by ernestoaguaysol** [comment]
CoS: El sistema permitirá desasignar un paciente a un turno, pudiendo asignarlo en otro y quedando registrado el último cambio.

**Comment by ernestoaguaysol** [comment]
Se cambia desde Turnos Reservados > Pacientes > Turnos Reservados > Cambiar turno

**Comment by alandavidg** [comment]
Que aparezcan los turnos posteriores a la fecha actual, en la pantalla con tìtulo "Buscar turno para cambiar"

**Comment by ernestoaguaysol** [comment]
Listo
