### ISSUE TITLE
REQ 30 Como secretaria deseo crear un sobreturno

### ISSUE THREAD

**Issue by ismaelpadilla2007** [Sistemas-de-Software/WebAppMedOffices#25]

**Comment by ernestoaguaysol** [comment]
CoS: El sistema permitirá crear sobreturnos, con datos de fecha, médico, sala y paciente.

**Comment by ernestoaguaysol** [comment]
Se agrega sobreturno desde **Asignar Turno**, aparece un nuevo botón **Sobreturno**, luego elige de la lista que **Asignar Sobreturno** , al elegir se crea un nuevo sobreturno con la fecha, especialidad, médico (con su sala asignada) sin importar la hora. 

Se hicieron mejoras en el listado de **Turnos Reservados** y **Turnos de Hoy**.
También se hicieron mejoras en el listado de **Pacientes del Día** del Médico.

Todas las mejoras son en la vista para distinguir un turno de un sobreturno.

**Comment by ismaelpadilla2007** [comment]
Cumple satisfactoriamente el CoS, pero como mejora estaría bueno que la fecha aparezca una sola vez en la lista de **Asignar Sobreturno**.

**Comment by alandavidg** [comment]
Exacto lo que dice Padi, hacer un distinct ahí, cuando los datos de especialidad, médico y fecha sean iguales, que aparezca solo una vez

**Comment by ernestoaguaysol** [comment]
si, la verdad que por cuestión de tiempo no pude investigar como se agrupan o usar un distinct  con EF, es algo que quedará pendiente para la próxima

**Comment by alandavidg** [comment]
Que aparezcan turnos posteriores a la fecha actual

**Comment by ernestoaguaysol** [comment]
Listo

**Comment by ernestoaguaysol** [comment]
Falta que aparezcan solo los turnos iguales o posteriores a la fecha actual

**Comment by ernestoaguaysol** [comment]
- [x]  BUG: Falta que aparezcan solo los turnos iguales o posteriores a la fecha actual.
- [x] BUG: Falta que aparezca solo un registro en caso de que fecha, especialidad y médico sean los mismos
