### ISSUE TITLE
REQ 19 Como médico deseo agregar comentarios a la ficha del paciente

### ISSUE THREAD

**Issue by ismaelpadilla2007** [Sistemas-de-Software/WebAppMedOffices#26]

**Comment by ismaelpadilla2007** [comment]
Según el CoS definido, solo faltaría **"agregar/modificar patologías y alergias que tenga el paciente"**

**Comment by ernestoaguaysol** [comment]
**CoS:**
El sistema permitirá agregar comentarios a la ficha médica de los pacientes. Lo podrá hacer desde la visualización de la ficha médica, mediante el botón "Agregar comentarios" y lo llevará a otra pantalla donde pueda escribir y guardar los cambios. A su vez, podrá agregar/modificar patologías y alergias que tenga el paciente.

**Comment by ernestoaguaysol** [comment]
agregar/modificar patologías y alergias se hizo con un botón aparte como propuesta de mejora.
