### ISSUE TITLE
Req 15 - Como secretaria deseo imprimir el listado de pacientes del día para cada médico

### ISSUE THREAD

**Issue by alandavidg** [Sistemas-de-Software/WebAppMedOffices#27]
El sistema permitirá imprimir el listado de los pacientes del día de cada médico, con su respectivo horario

**Comment by ernestoaguaysol** [comment]
Está lista una primera versión de imprimir turnos de hoy, si bien aparecen todos los médicos, se puede usar el buscados para que solo aparezca el médico que busca.

**Comment by ernestoaguaysol** [comment]
Otra opción sería poner una lista de médicos antes de ver los turnos de hoy.

**Comment by alandavidg** [comment]
Me gusta más la 1era opción, y asegurarse que filtre solo por médico y que el buscador no busque en pacientes (mas comodidad y precisión).

**Comment by ernestoaguaysol** [comment]
Listo solo se filtra la columna de Médicos
