### ISSUE TITLE
REQ 27 Como secretaria deseo crear/cargar un nuevo turno

### ISSUE THREAD

**Issue by ismaelpadilla2007** [Sistemas-de-Software/WebAppMedOffices#3]

**Comment by ernestoaguaysol** [comment]
CoS: El sistema permitirá crear turnos con la siguiente información: Fecha (Día y hora), médico y consultorio.

**Comment by ernestoaguaysol** [comment]
Se mejoró las validaciones siguientes:
La fecha Desde no puede ser mayor que la fecha Hasta.
La fecha Desde no puede ser menor que la fecha de Hoy.
Ya hay turnos cargados dentro del rango de fechas elegido. 

La última es la más complicada, por lo que se decidió solo cargar si no existen turnos dentro del rango elegido.

**Comment by alandavidg** [comment]
Buenísimo! Lo único que si el médico no tiene especialidad asignada no deja crear el turno.

**Comment by ernestoaguaysol** [comment]
Claro, por que cada espacialidad tiene una duración de atención, eso se definió como regla de negocio, que un médico puede tener muchas especialidades y que cada especialidad tiene una determinada duración.

**Comment by alandavidg** [comment]
El médico debe tener al menos una especialidad, entonces que se cargue al momento de dar de alta el médico.
El médico no va a tener especialidad? Que no sea obligatorio escoger una en la pantalla de crear nuevo turno.

**Comment by ernestoaguaysol** [comment]
La especialidad es obligatoria para poder cargar turnos, como ya lo dije en el audio, eso se carga por aparte, lo que se debería juntar es Consultorios y Especialidades en un Maestro detalle, por se están separados. En el REQ 1 [Como administrador deseo dar de alta un médico](https://github.com/Sistemas-de-Software/WebAppMedOffices/issues/1) debería estar esta validación de especialidades. 

Lo que veo es que nunca se habilitó ni siquiera esa carga de especialidades, ahora lo habilito para que puedas cargar esas especialidades por separado al menos por ahora.

**Comment by ernestoaguaysol** [comment]
Listo ahí agregué para que se pueda cargar la especialidad de un médico, provisoriamente por separado. Desde Médicos > Cargar especialidad a médico.

**Comment by alandavidg** [comment]
Bueno, si puede ser que aparezca nombre completo del doctor en el listado.
Por otro lado, la duración del turno que especifique que es en minutos: "Duración turno (minutos):"
Y bueno, por ahora lo dejamos ahí. Si luego de crear un medico aparece esta pantalla nueva mejor

**Comment by alandavidg** [comment]
Por otro lado, si el médico ya tiene una especialidad, que no le aparezca en el combo

**Comment by ernestoaguaysol** [comment]
dale dale, todo eso va en el REQ 1, aunque quizá convenga hacer otro REQ con los CoS específicos que decís para la carga de Especialidades a un médico.

**Comment by alandavidg** [comment]
Luego de cargar/crear un nuevo turno, que aparezca la pantalla "Turnos disponibles", para visualizar los cambios realizados (si aparecen los turnos disponibles de dicho médico mejor). Referencia:M-14

**Comment by alandavidg** [comment]
Si se asigna una especialidad que tarda 60 minutos y se asigna un consultorio por 60 minutos, no permite crear el turno (Bug-13)

**Comment by ernestoaguaysol** [comment]
Bug 13 solucionado 💯
