### ISSUE TITLE
Req 22 - Como secretaria deseo imprimir la liquidación mensual por obra social

### ISSUE THREAD

**Issue by alandavidg** [Sistemas-de-Software/WebAppMedOffices#30]
El sistema permitirá obtener la liquidación mensual por obra social, de pacientes que concurrieron a las consultas. Los datos que tendrá son: Nombre, Apellido, Nro de afiliado y Fecha en la que concurrió el paciente; Nombre, Apellido y Código del médico y Nombre de la Obra Social.

**Comment by alandavidg** [comment]
Al haber asistido a dos turnos en un mismo día, me aparece solo uno en la liquidación. CP-33 (Bug-11)

**Comment by ernestoaguaysol** [comment]
Dos turnos del mismo paciente? o de diferentes?

**Comment by alandavidg** [comment]
Realizado
