### ISSUE TITLE
Req 21 - Como secretaria deseo imprimir la liquidación semanal de pacientes atendidos de forma particular

### ISSUE THREAD

**Issue by alandavidg** [Sistemas-de-Software/WebAppMedOffices#31]
El sistema permitirá obtener la liquidación semanal de los pacientes atendidos de forma particular, con datos del nombre del paciente, fecha y monto de las consultas

**Comment by ernestoaguaysol** [comment]
Se agrega menú Gestión Liquidación y dentro Liquidación Paciente Particular

**Comment by alandavidg** [comment]
Si el paciente tiene 2 turnos distintos con dos médicos, solo aparece 1 de ellos en la liquidación, aunque se hayan hecho comentario en la ficha médica en ambos casos

**Comment by ernestoaguaysol** [comment]
Lo que hace (Basado en lo que dijo Dami) es una sumatoria de los costos de los turnos por más que se haya atendido con otros médicos, es decir que siempre aparece una sola vez el paciente en la lista de liquidaciones por paciente.

**Comment by ernestoaguaysol** [comment]
Hay dos cuestiones, lo que plantea Dami me parece bien ya queme parece innecesario repetir pacientes, pero el CoS quiere la fecha del turno, para mi eso no va, y si iría una sola fecha del día de la liquidación al final del listado quizás.
