### ISSUE TITLE
ACT 4 Juntar “turnos disponibles” (por especialidad o médico) con “asignar turno".

### ISSUE THREAD

**Issue by ernestoaguaysol** [Sistemas-de-Software/WebAppMedOffices#34]

**Comment by ernestoaguaysol** [comment]
Se junta turno disponibles con asignar turno.

**Comment by alandavidg** [comment]
Buenísimo. Pero porfa que quede en el menú "Turnos disponibles", para que se cumpla el req-12, sin que haya que entrar a un paciente para que se puedan visualizar los turnos disponibles
