### ISSUE TITLE
ACT 6 En “Cancelar turno por médico” que se pueda escoger un rango de fechas “desde-hasta”

### ISSUE THREAD

**Issue by ernestoaguaysol** [Sistemas-de-Software/WebAppMedOffices#36]

**Comment by ernestoaguaysol** [comment]
Se elimina turno por rango, cosas a tener en cuenta:
- Se elimina solo los turnos a partir de hoy 
- No se eliminan los turnos de hoy con estado "Atendido", eso se puede corroborar desde control de turnos.
- Validaciones de fechas cruzadas

**Comment by alandavidg** [comment]
Buenisimo
