### ISSUE TITLE
ACT 7 En la Liquidación de particulares poder listar paciente, fecha, hora y costo del turno. Además, poder mostrar los totales del día.

### ISSUE THREAD

**Issue by ernestoaguaysol** [Sistemas-de-Software/WebAppMedOffices#46]

**Comment by ernestoaguaysol** [comment]
Bueno sinceramente hay que ver como funcionaría este algoritmo con un mes de turnos a liquidar, y otra cosa que si bien están separados por médicos y especialidad, en el caso que un médico tuviera dos especialidades no los imprime como: Médico | Especialidad | Especialidad.... si no como: Médico | Especialidad | Médico (El mismo) | Especialidad. Pero es a lo que se llegó 👍

**Comment by alandavidg** [comment]
Està buenìsimo. Para mi no le falta nada
