### ISSUE TITLE
ACT 10 En Consultorio asignados agregar filtro de médico y especialidad

### ISSUE THREAD

**Issue by ernestoaguaysol** [Sistemas-de-Software/WebAppMedOffices#48]

**Comment by ernestoaguaysol** [comment]
@alandavidg  acá hay un problema, ya que los consultorios no dependen de la especialidad, un médico puede tener varias especialidades y atender en el mismo consultorio. Depende más del turno como se habilitó que del consultorio.
Lo que podemos hacer es poner solo el filtro por médicos (columna nombre y apellido). Que decís?

**Comment by ernestoaguaysol** [comment]
El filtro me parece más lógico que sea por sala y por médico.

**Comment by alandavidg** [comment]
Okas, donde está ese filtro? Decime la ruta para llegar porfa

**Comment by ernestoaguaysol** [comment]
Solo se llega al asignar un consultorio a un Médico, pero ahora dejo en el menú de Gestión de Médicos

**Comment by ernestoaguaysol** [comment]
Listo, como administrador aparece un nuevo menú en Gestión Médicos: Consultorios Asignados

**Comment by alandavidg** [comment]
Resuelve el Req-17, gracias!

**Comment by alandavidg** [comment]
El objetivo, según el título, es que el filtro que aparece solo afecte a médico y consultorio, verdad? En ese caso, por el CP-54, filtra también horarios y días de la semana (Bug-15)

**Comment by ernestoaguaysol** [comment]
Sisi, ok entonces ahora arreglo eso y lo mando a test

**Comment by ernestoaguaysol** [comment]
Listo, se filtra solo por Consultorio o Médico
