### ISSUE TITLE
REQ 3 Como administrador deseo dar de baja un médico

### ISSUE THREAD

**Issue by ernestoaguaysol** [Sistemas-de-Software/WebAppMedOffices#54]

**Comment by ernestoaguaysol** [comment]
Consideraciones al dar de baja un médico:
- No se puede dar de baja un médico con la agenda habilitada, es decir si tiene turnos cargados desde la fecha actual en adelante.
- Solo se puede eliminar un médico si no posee turnos cargados. Se elimina también las asociaciones de especialidades y consultorios.
- Por ahora no se puede dar de baja un médico con turnos antiguos atendidos, en ese caso sale una alerta de que se está trabajando para solucionar el problema. (caso de ocultar médico).

**Comment by alandavidg** [comment]
Ok, testeado
