### ISSUE TITLE
REQ 13 Como secretaria deseo registrar los pacientes ausentes del día

### ISSUE THREAD

**Issue by ernestoaguaysol** [Sistemas-de-Software/WebAppMedOffices#55]

**Comment by ernestoaguaysol** [comment]
Bueno te envío unos avances de como está quedando la cosa, se ingresa desde menú Gestión de Turnos / Control de Turnos, luego se elige la fecha, y trae un listado con los turnos de ese día. En el listado hay un botón de Ausente y al hacer click cambia en estado.

Algunas consideraciones que se tuvieron en cuenta son:

- Que no se pueda elegir una fecha mayor a la de hoy.
- El listado trae todo excepto los turnos con estado "Disponibles" ya que no fueron asignados a ningún paciente.
- Solo se puede cambiar el estado a **Ausente** cuando es un turno con estado **Reservado**
- Aparecen varias etiquetas tres colores, rojo Ausente, Amarillo Reservado, y para el resto celeste.

**Comment by alandavidg** [comment]
Muy buena la pantalla!
Tal vez el label fecha hasta le pondría solo fecha, ya que es por día.

**Comment by ernestoaguaysol** [comment]
Jaja quedó del copy paste, ahora lo arreglo

**Comment by ernestoaguaysol** [comment]
Listo, arreglado
