### ISSUE TITLE
REQ 4 Como secretaria deseo dar de alta un paciente

### ISSUE THREAD

**Issue by ismaelpadilla2007** [Sistemas-de-Software/WebAppMedOffices#6]
El sistema permite poner fecha de nacimiento posterior a la fecha actual

**Comment by alandavidg** [comment]
Deja poner fecha de nacimiento posterior a la fecha actual

**Comment by ismaelpadilla2007** [comment]
Validado fecha de nacimiento para que no sea mayor al día actual

**Comment by alandavidg** [comment]
Falta pedir el dato del email

**Comment by alandavidg** [comment]
Cambiar "ObraSocialId" por "Obra Social"

**Comment by ismaelpadilla2007** [comment]
Listo

**Comment by alandavidg** [comment]
Como mejora: Si se especifica una fecha superior a la del dia de la fecha como fecha de nacimiento, que no borre toda la info cargada

**Comment by alandavidg** [comment]
Falta que pida el número de afiliado, en caso de tener obra social

**Comment by alandavidg** [comment]
Estaría bueno también que no sean obligatorios los contactos de emergencia

**Comment by ismaelpadilla2007** [comment]
Listo!

**Comment by alandavidg** [comment]
Si no cargo obra social, me aparece el error: Cannot insert duplicate key row in object 'dbo.Pacientes' with unique index 'Paciente_ObraSocialId_NroAfiliado_Index'. The duplicate key value is (1, <NULL>).

**Comment by ismaelpadilla2007** [comment]
Solucionado! 
Ademas se agregaron validaciones

**Comment by alandavidg** [comment]
Permite dejar vacío el campo N° de Afiliado, el cual debería ser obligatorio si tiene obra social (Bug-07)

**Comment by ismaelpadilla2007** [comment]
Solucionado!
