### ISSUE TITLE
REQ 10 Como secretaria deseo registrar un paciente a un turno

### ISSUE THREAD

**Issue by ismaelpadilla2007** [Sistemas-de-Software/WebAppMedOffices#7]
Verificar si cumple con la condición de satisfacción establecida

**Comment by alandavidg** [comment]
Puede ser que si se crea una obra social y luego se le asigna a un nuevo paciente y se intenta asignar un turno a ese paciente, de error?
A mi me da error, quizá es algo de mi modelo. Si podés confirmalo porfa

**Comment by ismaelpadilla2007** [comment]
Realice los pasos que realizaste y da error!
Verifico el bug.

**Comment by ismaelpadilla2007** [comment]
El error es porque al crear una nueva obra social, se le debe asignar también una tarifa en las diferentes especialidades.
Los pasos para que se realice correctamente por el momento es:
Crear una obra social --> Cargar Tarifas por especialidad --> Crear Paciente --> Asignar turno.

**Comment by alandavidg** [comment]
Permite registrar un paciente a un turno anterior a la fecha actual, desde "Detalle del paciente", es decir, se listan turnos anteriores al día actual desde esa ruta (Bug-08)

**Comment by ismaelpadilla2007** [comment]
Solucionado!

**Comment by alandavidg** [comment]
Me sigue apareciendo turnos anteriores desde Detalle de paciente -> Asignar turnos

**Comment by ismaelpadilla2007** [comment]
Solucionado!
