### ISSUE TITLE
REQ 12 Como secretaria deseo visualizar los turnos disponibles por médico o especialidad

### ISSUE THREAD

**Issue by ismaelpadilla2007** [Sistemas-de-Software/WebAppMedOffices#8]

**Comment by alandavidg** [comment]
Estaría buena una pantalla anterior que permita elección de médico o especialidad, como la que hay para visualizar turnos reservados, pero sin "pacientes"

**Comment by ernestoaguaysol** [comment]
Ya está hecho en el ultimo commit. Si no te aparece decime y te creo un Tag

**Comment by alandavidg** [comment]
Al ser un turno disponible creo que nunca tendría asignado un paciente y obra social (precio quizá tampoco, ya que se determinará según el paciente y su obra social). Por eso esas columnas tal vez se puedan excluir.

**Comment by alandavidg** [comment]
Tendría que mostrar los turnos disponibles a partir de la fecha actual

**Comment by ernestoaguaysol** [comment]
Listo

**Comment by alandavidg** [comment]
En turnos disponibles por especialidad, que ordene por fecha y hora, en vez de por médico (M-11 y M-16)
