### ISSUE TITLE
REQ 18 Como médico deseo visualizar la ficha del paciente

### ISSUE THREAD

**Issue by ismaelpadilla2007** [Sistemas-de-Software/WebAppMedOffices#9]

**Comment by alandavidg** [comment]
Cada médico puede ver la ficha de todos los pacientes, faltaría que solo pueda ver solo las de sus pacientes

**Comment by ernestoaguaysol** [comment]
Osea los pacientes que alguna vez atendió? por que por ejemplo un paciente puede sacar turno para traumatología pero el médico puede ser diferente. Si es solo los pacientes que haya atendido se puede hacer, si no hay que contemplar algo que no estaba que es que un paciente tiene un Médico principal por cada espacialidad y además puede ser atendido por otro médico de la misma especialidad.

**Comment by alandavidg** [comment]
Bueno, habría que corregir lo que dijo Lucas... que lo pueda visualizar a sus pacientes y comentarios de otros médicos que lo atendieron

**Comment by ernestoaguaysol** [comment]
En ficha médica se divide en Historia Clínica de pacientes atendidos por un médico e Historia Clínica de pacientes atendidos por otros médicos

**Comment by alandavidg** [comment]
Ya que la historia clínica es de un paciente:
Cambiar "Historia Clínica de mis pacientes" por "Historia clinica atendida por mi"
y Historia Clínica de pacientes atendidos por otros médicos por "historia clínica del paciente por otros médicos" o  "historia clínica por otros médicos"

**Comment by ernestoaguaysol** [comment]
Listo el cambio de texto
